version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web_scrapper:
    build: .
    container_name: web_scrapper
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    working_dir: /app
    command: ["bash", "-c", "pip install -r requirements.txt && python pipe.py"]
volumes:
  postgres_data:
